#!/usr/bin/env bash

LINUXDEPLOY_TOOLS_DIR="$1"
LINUXDEPLOY_INTERMEDIATE_APPIMAGE="$2"
LINUXDEPLOY_RUNTIME_FILE="$3"

export ARCH=x86_64
export APPIMAGE_EXTRACT_AND_RUN=1
export PATH="$LINUXDEPLOY_TOOLS_DIR:$PATH"
export LDAI_NO_APPSTREAM=1
export LDAI_OUTPUT="$LINUXDEPLOY_INTERMEDIATE_APPIMAGE"
export LDAI_RUNTIME_FILE="$LINUXDEPLOY_RUNTIME_FILE"

unset LINUXDEPLOY_TOOLS_DIR LINUXDEPLOY_INTERMEDIATE_APPIMAGE LINUXDEPLOY_RUNTIME_FILE
